version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pw
    ports:
      - 5433:5432